const data=[

  { id: 1,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "none",
    approve: true,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  },
  { id: 2,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "None",
    approve: true,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  },
  { id: 3,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "none",
    approve: true,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  },
  { id: 4,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "none",
    approve: true,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  },
  { id: 5,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "none",
    approve: true,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  },
  { id: 6,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "none",
    approve: true,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  },
  { id: 7,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "none",
    approve: true,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  }, 
  { id: 8,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "sem 1: clp sem 2: vee sem 1: clp sem 2: vee",
    approve: false,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  },
  { id: 9,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "cp",
    approve: false,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  },
  { id: 10,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "Be",
    approve: false,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  },
  { id: 11,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "tce",
    approve: false,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  },
  { id: 12,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "asd",
    approve: false,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  },
  { id: 13,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "be-lab",
    approve: false,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  },
  { id: 14,
    Rollno  : "21ucc041" ,
    Name : "Gaurav Agrawal",
    Activeb : "xyz"
    ,
    approve: false,
    Phoneno:" 11324234" ,
    Gender: "Male",
    branch : "cce",
    In:false
  }]
  export default data;